/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/_dashboard/route'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard/index'
import { Route as DashboardProductsIndexRouteImport } from './routes/_dashboard/products/index'
import { Route as DashboardComponentsIndexRouteImport } from './routes/_dashboard/components/index'
import { Route as DashboardCategoriesIndexRouteImport } from './routes/_dashboard/categories/index'
import { Route as DashboardBrandsIndexRouteImport } from './routes/_dashboard/brands/index'
import { Route as DashboardProductsProductIdRouteImport } from './routes/_dashboard/products/$productId'
import { Route as DashboardCategoriesCategoryIdRouteImport } from './routes/_dashboard/categories/$categoryId'
import { Route as DashboardBrandsBrandIdRouteImport } from './routes/_dashboard/brands/$brandId'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardProductsIndexRoute = DashboardProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardComponentsIndexRoute =
  DashboardComponentsIndexRouteImport.update({
    id: '/components/',
    path: '/components/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardCategoriesIndexRoute =
  DashboardCategoriesIndexRouteImport.update({
    id: '/categories/',
    path: '/categories/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardBrandsIndexRoute = DashboardBrandsIndexRouteImport.update({
  id: '/brands/',
  path: '/brands/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardProductsProductIdRoute =
  DashboardProductsProductIdRouteImport.update({
    id: '/products/$productId',
    path: '/products/$productId',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardCategoriesCategoryIdRoute =
  DashboardCategoriesCategoryIdRouteImport.update({
    id: '/categories/$categoryId',
    path: '/categories/$categoryId',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardBrandsBrandIdRoute = DashboardBrandsBrandIdRouteImport.update({
  id: '/brands/$brandId',
  path: '/brands/$brandId',
  getParentRoute: () => DashboardRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof DashboardIndexRoute
  '/login/': typeof LoginIndexRoute
  '/brands/$brandId': typeof DashboardBrandsBrandIdRoute
  '/categories/$categoryId': typeof DashboardCategoriesCategoryIdRoute
  '/products/$productId': typeof DashboardProductsProductIdRoute
  '/brands/': typeof DashboardBrandsIndexRoute
  '/categories/': typeof DashboardCategoriesIndexRoute
  '/components/': typeof DashboardComponentsIndexRoute
  '/products/': typeof DashboardProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof DashboardIndexRoute
  '/login': typeof LoginIndexRoute
  '/brands/$brandId': typeof DashboardBrandsBrandIdRoute
  '/categories/$categoryId': typeof DashboardCategoriesCategoryIdRoute
  '/products/$productId': typeof DashboardProductsProductIdRoute
  '/brands': typeof DashboardBrandsIndexRoute
  '/categories': typeof DashboardCategoriesIndexRoute
  '/components': typeof DashboardComponentsIndexRoute
  '/products': typeof DashboardProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteRouteWithChildren
  '/_dashboard/': typeof DashboardIndexRoute
  '/login/': typeof LoginIndexRoute
  '/_dashboard/brands/$brandId': typeof DashboardBrandsBrandIdRoute
  '/_dashboard/categories/$categoryId': typeof DashboardCategoriesCategoryIdRoute
  '/_dashboard/products/$productId': typeof DashboardProductsProductIdRoute
  '/_dashboard/brands/': typeof DashboardBrandsIndexRoute
  '/_dashboard/categories/': typeof DashboardCategoriesIndexRoute
  '/_dashboard/components/': typeof DashboardComponentsIndexRoute
  '/_dashboard/products/': typeof DashboardProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login/'
    | '/brands/$brandId'
    | '/categories/$categoryId'
    | '/products/$productId'
    | '/brands/'
    | '/categories/'
    | '/components/'
    | '/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/brands/$brandId'
    | '/categories/$categoryId'
    | '/products/$productId'
    | '/brands'
    | '/categories'
    | '/components'
    | '/products'
  id:
    | '__root__'
    | '/_dashboard'
    | '/_dashboard/'
    | '/login/'
    | '/_dashboard/brands/$brandId'
    | '/_dashboard/categories/$categoryId'
    | '/_dashboard/products/$productId'
    | '/_dashboard/brands/'
    | '/_dashboard/categories/'
    | '/_dashboard/components/'
    | '/_dashboard/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  LoginIndexRoute: typeof LoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/products/': {
      id: '/_dashboard/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof DashboardProductsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/components/': {
      id: '/_dashboard/components/'
      path: '/components'
      fullPath: '/components/'
      preLoaderRoute: typeof DashboardComponentsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/categories/': {
      id: '/_dashboard/categories/'
      path: '/categories'
      fullPath: '/categories/'
      preLoaderRoute: typeof DashboardCategoriesIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/brands/': {
      id: '/_dashboard/brands/'
      path: '/brands'
      fullPath: '/brands/'
      preLoaderRoute: typeof DashboardBrandsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/products/$productId': {
      id: '/_dashboard/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof DashboardProductsProductIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/categories/$categoryId': {
      id: '/_dashboard/categories/$categoryId'
      path: '/categories/$categoryId'
      fullPath: '/categories/$categoryId'
      preLoaderRoute: typeof DashboardCategoriesCategoryIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/brands/$brandId': {
      id: '/_dashboard/brands/$brandId'
      path: '/brands/$brandId'
      fullPath: '/brands/$brandId'
      preLoaderRoute: typeof DashboardBrandsBrandIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardBrandsBrandIdRoute: typeof DashboardBrandsBrandIdRoute
  DashboardCategoriesCategoryIdRoute: typeof DashboardCategoriesCategoryIdRoute
  DashboardProductsProductIdRoute: typeof DashboardProductsProductIdRoute
  DashboardBrandsIndexRoute: typeof DashboardBrandsIndexRoute
  DashboardCategoriesIndexRoute: typeof DashboardCategoriesIndexRoute
  DashboardComponentsIndexRoute: typeof DashboardComponentsIndexRoute
  DashboardProductsIndexRoute: typeof DashboardProductsIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardBrandsBrandIdRoute: DashboardBrandsBrandIdRoute,
  DashboardCategoriesCategoryIdRoute: DashboardCategoriesCategoryIdRoute,
  DashboardProductsProductIdRoute: DashboardProductsProductIdRoute,
  DashboardBrandsIndexRoute: DashboardBrandsIndexRoute,
  DashboardCategoriesIndexRoute: DashboardCategoriesIndexRoute,
  DashboardComponentsIndexRoute: DashboardComponentsIndexRoute,
  DashboardProductsIndexRoute: DashboardProductsIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  LoginIndexRoute: LoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
