/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteRouteImport } from './routes/_authed/route'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedProductsIndexRouteImport } from './routes/_authed/products/index'
import { Route as AuthedComponentsIndexRouteImport } from './routes/_authed/components/index'
import { Route as AuthedCategoriesIndexRouteImport } from './routes/_authed/categories/index'
import { Route as AuthedBrandsIndexRouteImport } from './routes/_authed/brands/index'
import { Route as AuthedProductsProductIdRouteImport } from './routes/_authed/products/$productId'
import { Route as AuthedCategoriesCategoryIdRouteImport } from './routes/_authed/categories/$categoryId'
import { Route as AuthedBrandsBrandIdRouteImport } from './routes/_authed/brands/$brandId'

const AuthedRouteRoute = AuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedProductsIndexRoute = AuthedProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedComponentsIndexRoute = AuthedComponentsIndexRouteImport.update({
  id: '/components/',
  path: '/components/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedCategoriesIndexRoute = AuthedCategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedBrandsIndexRoute = AuthedBrandsIndexRouteImport.update({
  id: '/brands/',
  path: '/brands/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedProductsProductIdRoute = AuthedProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedCategoriesCategoryIdRoute =
  AuthedCategoriesCategoryIdRouteImport.update({
    id: '/categories/$categoryId',
    path: '/categories/$categoryId',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedBrandsBrandIdRoute = AuthedBrandsBrandIdRouteImport.update({
  id: '/brands/$brandId',
  path: '/brands/$brandId',
  getParentRoute: () => AuthedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login/': typeof LoginIndexRoute
  '/brands/$brandId': typeof AuthedBrandsBrandIdRoute
  '/categories/$categoryId': typeof AuthedCategoriesCategoryIdRoute
  '/products/$productId': typeof AuthedProductsProductIdRoute
  '/brands/': typeof AuthedBrandsIndexRoute
  '/categories/': typeof AuthedCategoriesIndexRoute
  '/components/': typeof AuthedComponentsIndexRoute
  '/products/': typeof AuthedProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginIndexRoute
  '/brands/$brandId': typeof AuthedBrandsBrandIdRoute
  '/categories/$categoryId': typeof AuthedCategoriesCategoryIdRoute
  '/products/$productId': typeof AuthedProductsProductIdRoute
  '/brands': typeof AuthedBrandsIndexRoute
  '/categories': typeof AuthedCategoriesIndexRoute
  '/components': typeof AuthedComponentsIndexRoute
  '/products': typeof AuthedProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteRouteWithChildren
  '/_authed/': typeof AuthedIndexRoute
  '/login/': typeof LoginIndexRoute
  '/_authed/brands/$brandId': typeof AuthedBrandsBrandIdRoute
  '/_authed/categories/$categoryId': typeof AuthedCategoriesCategoryIdRoute
  '/_authed/products/$productId': typeof AuthedProductsProductIdRoute
  '/_authed/brands/': typeof AuthedBrandsIndexRoute
  '/_authed/categories/': typeof AuthedCategoriesIndexRoute
  '/_authed/components/': typeof AuthedComponentsIndexRoute
  '/_authed/products/': typeof AuthedProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login/'
    | '/brands/$brandId'
    | '/categories/$categoryId'
    | '/products/$productId'
    | '/brands/'
    | '/categories/'
    | '/components/'
    | '/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/brands/$brandId'
    | '/categories/$categoryId'
    | '/products/$productId'
    | '/brands'
    | '/categories'
    | '/components'
    | '/products'
  id:
    | '__root__'
    | '/_authed'
    | '/_authed/'
    | '/login/'
    | '/_authed/brands/$brandId'
    | '/_authed/categories/$categoryId'
    | '/_authed/products/$productId'
    | '/_authed/brands/'
    | '/_authed/categories/'
    | '/_authed/components/'
    | '/_authed/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRouteRoute: typeof AuthedRouteRouteWithChildren
  LoginIndexRoute: typeof LoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/products/': {
      id: '/_authed/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof AuthedProductsIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/components/': {
      id: '/_authed/components/'
      path: '/components'
      fullPath: '/components/'
      preLoaderRoute: typeof AuthedComponentsIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/categories/': {
      id: '/_authed/categories/'
      path: '/categories'
      fullPath: '/categories/'
      preLoaderRoute: typeof AuthedCategoriesIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/brands/': {
      id: '/_authed/brands/'
      path: '/brands'
      fullPath: '/brands/'
      preLoaderRoute: typeof AuthedBrandsIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/products/$productId': {
      id: '/_authed/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof AuthedProductsProductIdRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/categories/$categoryId': {
      id: '/_authed/categories/$categoryId'
      path: '/categories/$categoryId'
      fullPath: '/categories/$categoryId'
      preLoaderRoute: typeof AuthedCategoriesCategoryIdRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/brands/$brandId': {
      id: '/_authed/brands/$brandId'
      path: '/brands/$brandId'
      fullPath: '/brands/$brandId'
      preLoaderRoute: typeof AuthedBrandsBrandIdRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
  }
}

interface AuthedRouteRouteChildren {
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedBrandsBrandIdRoute: typeof AuthedBrandsBrandIdRoute
  AuthedCategoriesCategoryIdRoute: typeof AuthedCategoriesCategoryIdRoute
  AuthedProductsProductIdRoute: typeof AuthedProductsProductIdRoute
  AuthedBrandsIndexRoute: typeof AuthedBrandsIndexRoute
  AuthedCategoriesIndexRoute: typeof AuthedCategoriesIndexRoute
  AuthedComponentsIndexRoute: typeof AuthedComponentsIndexRoute
  AuthedProductsIndexRoute: typeof AuthedProductsIndexRoute
}

const AuthedRouteRouteChildren: AuthedRouteRouteChildren = {
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedBrandsBrandIdRoute: AuthedBrandsBrandIdRoute,
  AuthedCategoriesCategoryIdRoute: AuthedCategoriesCategoryIdRoute,
  AuthedProductsProductIdRoute: AuthedProductsProductIdRoute,
  AuthedBrandsIndexRoute: AuthedBrandsIndexRoute,
  AuthedCategoriesIndexRoute: AuthedCategoriesIndexRoute,
  AuthedComponentsIndexRoute: AuthedComponentsIndexRoute,
  AuthedProductsIndexRoute: AuthedProductsIndexRoute,
}

const AuthedRouteRouteWithChildren = AuthedRouteRoute._addFileChildren(
  AuthedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthedRouteRoute: AuthedRouteRouteWithChildren,
  LoginIndexRoute: LoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
